displayName=RuneGlass
author=Jeroen Breevoort
description=Opt-in synchronization of your current character's skills, XP, and bird house timers with RuneGlass
tags=mobile,progress,skills,xp,timers,sync
plugins=com.runeglass.runelite.RuneGlassPlugin
build=standard
