displayName=RuneGlass
author=Jeroen Breevoort
description=Opt-in synchronization of your current character's skills and XP with RuneGlass
tags=mobile,progress,skills,xp,sync
plugins=com.runeglass.runelite.RuneGlassPlugin
build=standard
